pipeline {
    agent {
        docker {
            image 'jdsmoreira/ruby-web-agent'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparation'){
            steps{
                sh 'cd web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd web && rake local_seeds_jenkins'                
            }
        }
        stage('UAT - Homologação'){
            steps {
            echo 'Aguardando testes de aceitação.'
            input message: "Podemos ir para produção?"
            }
        }
        stage('Prod'){
            steps {
            echo 'WebApp pronta para produção :)'
            }
        }
    }
    post{
        always{
            allure includeProperties: false, jdk: '', results: [[path: 'web/logs']]
        }
    }
}
