require "digest/md5"

require_relative "features/support/libs/mongo"

def tod_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :teste do
  puts "Executando uma tarefa"
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

  users = [
    { name: "Roberto Carlos", email: "betao@yahoo.com", password: tod_md5("pwd123") },
    { name: "Jeferson Moreira", email: "jeferson@gmail.com", password: tod_md5("pwd123") },
    { name: "Spider Man", email: "spider@hotmail.com", password: tod_md5("pwd123") },
    { name: "João Anunciante", email: "joao@anunciante.com", password: tod_md5("pwd123") },
    { name: "Maria Locataria", email: "maria@locataria.com", password: tod_md5("pwd123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber"
end

task :local_seeds_jenkins do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

  users = [
    { name: "Roberto Carlos", email: "betao@yahoo.com", password: tod_md5("pwd123") },
    { name: "Jeferson Moreira", email: "jeferson@gmail.com", password: tod_md5("pwd123") },
    { name: "Spider Man", email: "spider@hotmail.com", password: tod_md5("pwd123") },
    { name: "João Anunciante", email: "joao@anunciante.com", password: tod_md5("pwd123") },
    { name: "Maria Locataria", email: "maria@locataria.com", password: tod_md5("pwd123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber -p jenkins"
end

task :hml_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hml.yml"))

  users = [
    { name: "Roberto Carlos", email: "betao@yahoo.com", password: tod_md5("pwd123") },
    { name: "Jeferson Moreira", email: "jeferson@gmail.com", password: tod_md5("pwd123") },
    { name: "Spider Man", email: "spider@hotmail.com", password: tod_md5("pwd123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber"
end
