source "https://rubygems.org"

gem "allure-cucumber", "2.13.6.3"
gem "capybara", "3.33"
gem "cucumber", "5.2"
gem "rspec", "3.9"
gem "rufo", "0.12.0"
gem "selenium-webdriver", "3.142.7"
gem "site_prism"
